volumes:
  example-index:
services:
  kalamar:
    image: "korap/kalamar:dnb"
    ports:
      - "4000:64543"
    environment:
      KALAMAR_API: "http://kustvakt:8089/api/"
    depends_on:
      - kustvakt
    volumes:
      - type: bind
        source: ./html/robots.txt
        target: /kalamar/public/robots.txt
      - type: bind
        source: ./kalamar.conf
        target: /kalamar/kalamar.conf
    profiles:
      - lite
    restart: "unless-stopped"
  kustvakt:
    environment:
      - INDEX=${INDEX:-${PWD}/dnb.index}
    image: "korap/kustvakt:0.73.2"
    ports:
      - "8089:8089"
    user: root
    volumes:
      - "${INDEX}:/kustvakt/index:z"
    profiles:
      - lite
    restart: "unless-stopped"
