version: '3.8'
volumes:
  example-index:
services:
  kalamar:
    image: "korap/kalamar:dnb"
    ports:
      - "4000:64543"
    environment:
      KALAMAR_API: "http://kustvakt:8089/api/"
    depends_on:
      - kustvakt
    volumes:
      - type: bind
        source: ./html/robots.txt
        target: /kalamar/public/robots.txt
    profiles:
      - lite
    restart: "unless-stopped"
  full-init:
    image: "korap/kalamar:latest-conv"
    command: super_client_info kalamar /kalamar/data/super_client_info
    volumes:
      - type: bind
        source: "${PWD}/data/"
        target: "/kalamar/data"
    profiles:
      - full
      - init
    user: root
    restart: "no"
  kustvakt:
    image: "korap/kustvakt:0.73.2"
    ports:
      - "8089:8089"
    user: root
    volumes:
      - "${PWD}/dnb.index:/kustvakt/index:z"
    profiles:
      - lite
    restart: "unless-stopped"
